voodooclothing2/config/routes.rb
Rails.application.routes.draw do
  get 'main/homepage', to: 'main#homepage', as: 'main'
  get 'welcome/index', to: 'welcome#index', as: 'welcome'

   root 'welcome#index'

end

voodooclothing2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

voodooclothing2/app/controllers/main_controller.rb
class MainController < ApplicationController
  def homepage
  end
end

voodooclothing2/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

voodooclothing2/app/helpers/application_helper.rb
module ApplicationHelper
end

voodooclothing2/app/helpers/main_helper.rb
module MainHelper
end

voodooclothing2/app/helpers/welcome_helper.rb
module WelcomeHelper
end

voodooclothing2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voodooclothing2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

voodooclothing2/app/views/main/homepage.html.erb
<body>
  <div class="section top">
    <div class="section-content">
      <%= link_to image_tag("feathers.png", class: "logo"), welcome_path %>
    </div>
  </div>

  <div class="section header">
    <div class="section-content">
      <h1 class="heading">Hugh's Website</h1>
    </div>
  </div>

  <div class="section about-me">
    <div class="section-content">
      <h3 class="about-header">About Me</h3>
    </div>
  </div>

  <div class="section type">
    <div class="section-content">
      <p class="type-text">
        This is voodoo clothing bitches
      </p>
    </div>

  </div>
</body>

voodooclothing2/app/views/welcome/index.html.erb
<div class="container">
  <div class="section">
    <div class="section-content welcome-backround">
      <div class="welcome-header">
        <%= link_to "Click to experience the voodoo experiecne", main_path %>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-content monkey">
      <%= image_tag("1.png", id: "img1") %>
      <%= image_tag("2.png", id: "img2") %>
      <%= image_tag("3.png", id: "img3") %>
      <%= image_tag("4.png", id: "img4") %>
    </div>
  </div>
</div>